#!/bin/bash

# Set the path to your Git repository (one folder up from the current directory)
PID_FILE=".npm_preview_pid"
PORT=80

# Function to start the npm preview
start_preview() {
    echo "Starting the web project with 'dotnet run'..."
    dotnet run & echo $! > "$PID_FILE"
}

stop_preview() {
    dotnet_pid=$(cat "$PID_FILE")
    kill -INT $dotnet_pid
}

cleanup() {
    echo "Cleaning up..."
    stop_preview
    exit 0
}

dotnet run

trap cleanup SIGINT

# Infinite loop to check for updates
while true; do
    # Fetch the latest changes from the remote repository
    git fetch

    # Check if there are any changes to pull
    if [ $(git rev-list HEAD...origin/main --count) -gt 0 ]; then
        echo "Changes detected. Pulling updates..."

        # Stop the old npm process
        stop_preview

        # Pull the latest changes
        git pull
        # Start the web project using dotnet run
        #
        start_preview
    else
        echo "No changes detected."
    fi

    # Wait for 5 seconds before checking again
    sleep 60
done
