// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MileageTrackerAPI;

#nullable disable

namespace MileageTrackerAPI.Migrations
{
    [DbContext(typeof(MileageDbContext))]
    [Migration("20250822035013_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MileageTrackerAPI.Models.MileageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Miles")
                        .HasColumnType("double");

                    b.Property<int>("SyncSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SyncSessionId");

                    b.ToTable("MileageLogs");
                });

            modelBuilder.Entity("MileageTrackerAPI.Models.SyncSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LinkingCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SyncSessions");
                });

            modelBuilder.Entity("MileageTrackerAPI.Models.MileageLog", b =>
                {
                    b.HasOne("MileageTrackerAPI.Models.SyncSession", "SyncSession")
                        .WithMany("MileageLogs")
                        .HasForeignKey("SyncSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncSession");
                });

            modelBuilder.Entity("MileageTrackerAPI.Models.SyncSession", b =>
                {
                    b.Navigation("MileageLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
